services:
  surrealdb:
    container_name: muse-surrealdb
    image: surrealdb/surrealdb:v2.0.0-alpha.9
    restart: always
    command: start -u ${DATABASE_USER} -p ${DATABASE_PASSWORD} --log trace file:/mydata/mydatabase.db
    user: root
    volumes:
      - surrealdb-data:/mydata/mydatabase.db
    ports:
      - "${DATABASE_PORT}:8000"
# ollama ui
#  open-webui:
#    container_name: open-webui
#    image: ghcr.io/open-webui/open-webui:main
#    restart: always
#    ports:
#      - "3000:8080"
#    volumes:
#      - open-webui:/app/backend/data
#    environment:
#      - WEBUI_AUTH=false
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

volumes:
#  open-webui:
  surrealdb-data:
