version: '3.8'

services:
  search-postgres:
    image: pgvector/pgvector:pg16
    container_name: search-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "5433:80"
    depends_on:
      - search-postgres
