# item
# 上海旅游
curl -X POST -H "Content-Type: application/json" -d '{"text":["上海路书｜连夜写的三天行程攻略 一定要看 还有两天就是五一了 连夜整理的攻略一定要看 不多不少，整理了一下三天的行程，这样玩还蛮舒服的，而且近期天气也好，祝大家玩的开心哟       住宿区域       南京路：地铁线密集，步行可到外滩       愚园路：有很多值得打卡的网红小店       陆家嘴：看夜景交通出行       伴手礼选择       ①大白兔奶糖：既是童年的回忆，却又是上海土生士长的糖果       ②城隍庙五香豆：选用余姚县的蚕豆，够香够糯，颗颗饱满       ③高桥松饼：每层的皮薄得像纸，吃起来妙酥，滋味较甜有松软       打卡过的上海美食       蟹叁寳 · 蟹黄捞饭：蟹粉春卷，外面酥酥脆脆的，里面的馅也有蟹粉，肉好嫩       阳春面：味道比较清淡，汤头鲜香可口，本地人都常吃的美食，清淡爽口       生煎包：生煎包可以说是土生土长的上海点心，据说已有上百年的历史       文案来咯       1.       𝑆ℎ𝑎𝑛𝑔ℎ𝑎𝑖       “这座城市就是最好的文案”       2.       𝑆ℎ𝑎𝑛𝑔ℎ𝑎𝑖 ｜初遇上海       3.       SHANGHAI ｜上海·外滩       4.       𝑆ℎ𝑎𝑛𝑔ℎ𝑎𝑖 总要去趟上海 吹吹黄浦江的晚风吧       上海 上海旅游 上海旅游攻略 上海酒店 上海美食 上海住宿 上海旅行 东方明珠 魔都 魔都探店 魔都美食 迪士尼 迪士尼乐园 假期去哪儿 五一去哪玩"],"image":["http://localhost:9000/muse/sh/1.png","http://localhost:9000/muse/sh/2.png","http://localhost:9000/muse/sh/3.png","http://localhost:9000/muse/sh/4.png","http://localhost:9000/muse/sh/5.png","http://localhost:9000/muse/sh/6.png","http://localhost:9000/muse/sh/7.png"]}' http://localhost:3000/inbound/item
# 北京旅游
curl -X POST -H "Content-Type: application/json" -d '{"text":[" 北京旅游攻略日 City walk打卡路线     北京两日city walk路线来啦！！   逛吃拍照 看这一篇就够了   Day1   天坛 门票28 推荐早上8:00入园拍出无人感   天安门广场 记得带上一个小红旗拍照很出片   国家博物馆 需提前预约 建议游玩2h以上   故宫博物院 门票40 提前一周预约   前门大街 适合晚上看看夜景 去逛吃   四季民福 每次去北京都要去这里吃烤鸭      Day2   五四大街 值得逛的店铺有很多 适合city walk   北海公园 门票5 古典的皇家园林   南锣鼓巷 有很多小吃和文艺店铺   鼓楼大街 来看一看赵雷的歌里的鼓楼   颐和园 20 山水亭台楼阁 画中游太美啦   东来顺 这家涮肉味道很不错      关于穿搭：   北京的红色建筑居多   穿黑色系或国风类型的衣服会更出片      关于美食：   涮肉：南门涮肉 八爷涮肉 东来顺   烤鸭：四季民福   炸酱面：方砖厂      关于酒店：   建议故宫附近或靠近地铁站的位置   属于打卡点中心 出行逛吃都方便        北京   北京旅游攻略  北京美食攻略   北京胡同   北京旅游   北京citywalk   北京旅行   北京旅行攻略   北京旅行必打卡景点   天安门   天安门广场   天安门看升旗   国家博物馆   故宫   故宫拍照   北京故宫博物院   北京鼓楼   颐和园   北京颐和园   颐和园攻略   画中游   天坛公园   天坛   祈年殿   天坛公园拍照   北海公园   北锣鼓巷    我的私藏旅行路线   南锣鼓巷   天坛拍照   北京旅游打卡   北京拍照打卡 @走走薯 @生活薯"],"image":["http://localhost:9000/muse/bg/1.png","http://localhost:9000/muse/bg/2.png","http://localhost:9000/muse/bg/3.png","http://localhost:9000/muse/bg/4.png","http://localhost:9000/muse/bg/5.png","http://localhost:9000/muse/bg/6.png","http://localhost:9000/muse/bg/7.png","http://localhost:9000/muse/bg/8.png","http://localhost:9000/muse/bg/9.png","http://localhost:9000/muse/bg/10.png","http://localhost:9000/muse/bg/11.png","http://localhost:9000/muse/bg/12.png","http://localhost:9000/muse/bg/13.png","http://localhost:9000/muse/bg/14.png","http://localhost:9000/muse/bg/15.png","http://localhost:9000/muse/bg/16.png"]}' http://localhost:3000/inbound/item
# 韩国旅游
curl -X POST -H "Content-Type: application/json" -d '{"text":["J人的首尔行｜3天逛吃买我都要！   朋友们都夸的首尔行，一张图就讲清楚啦！我将首尔分为西边，中间，东边三个片区，每天由最北边的景点为起点，一路向南。   天的行程各有主题各有特色！  Day   是核心旅游区，包括了热闹的商圈和传统景点。详细介绍见主页【首尔一日游】。主要路径为【光化门广场】-【景福宫】-【青瓦台】-【韩屋村】-【明洞】-【首尔塔】-【梨泰院】。【路线图见图2！】  Day   大学片区，超级有活力，很好逛！梨花女大真很美！（图5）主要路线为【梨花女子大学】-【延世大学】-【弘益大学】-【汝矣岛汉江公园】【路线图见图3！】  Day   包含了现在最火的打卡点，适合追星人和买买买！主要路线为【东大门设计广场】-【圣水洞】-【清潭洞】-【狎鸥亭】-【新沙洞】【路线图见图4！】   韩国旅游发展局  好好玩情报局   我去韩国撒个欢  红薯旅行家  j人旅行指南  圆周旅迹  首尔旅行  首尔旅游攻略  首尔逛街去哪  首尔探店  jennie同款  韩国旅游攻略  生活薯"],"image":["http://localhost:9000/muse/sk/1.png","http://localhost:9000/muse/sk/2.png","http://localhost:9000/muse/sk/3.png","http://localhost:9000/muse/sk/4.png","http://localhost:9000/muse/sk/5.png","http://localhost:9000/muse/sk/6.png","http://localhost:9000/muse/sk/7.png","http://localhost:9000/muse/sk/8.png","http://localhost:9000/muse/sk/9.png","http://localhost:9000/muse/sk/10.png","http://localhost:9000/muse/sk/11.png"]}' http://localhost:3000/inbound/item
# 爬山
curl -X POST -H "Content-Type: application/json" -d '{"text":["一张图讲清楚日爬泰山路线    春天就要上春山 红色路线：适合体力      步行上下，从红门➡️中天门➡️南天门➡️玉皇顶，再原路返回。爬泰山体验感强。 绿色：适合体力  大巴＋索道上下省时省力，但是只能看到玉皇顶附近景点，沿途景点错过。 红色＋绿色方案一：适合体力   稍费力能欣赏精华景点。从红门爬到中天门，在中天门坐缆车到南天门，步行至玉皇顶。（大多数选择的路线) 红色＋绿色方案二：适合体力    从天外村坐大巴车到中天门，从中天门爬到南天门，步行至玉皇顶。坡度较陡，体验爬山乐趣。 红色＋绿色方案三：适合体力     从红门爬到中天门，再爬到南天门，步行到玉皇顶，返回南天门做索道到中天门，大巴车到天外村。能欣赏全部景点，下山后到市里近。 红色+黄色：适合体力     从红门爬到中天门，再爬到南天门，步行到玉皇顶，返回南天门做索道到桃花源，做大巴到桃花峪，能欣赏全部景点和车览桃花源景色，但是下大巴后打车较远 住宿 建议住在岱庙附近，步行到岱庙几百米，步行到老县衙很近吃各种小吃。炸鸡、串串、麻辣烫、烧饼加肉等，岱庙附近还有夜市一条街。 其他游玩 1.  岱庙：爬泰山必去岱庙。岱庙不是个庙宇，是座有前年历史的古建筑群。 2.  泰安老街：名字叫老街，但是新建的，步行街标配的小吃！小吃街后面的公园灯光挺好看的！ 纪念品 可以买可爱的小狮子泰山石敢当做纪念品，泰山上的价格不如岱庙的便宜。  人文景点分享  泰山  泰山攻略  泰山旅游  泰山石敢当  泰山日爬"],"image":["http://localhost:9000/muse/climb/1.png","http://localhost:9000/muse/climb/2.png","http://localhost:9000/muse/climb/3.png","http://localhost:9000/muse/climb/4.png","http://localhost:9000/muse/climb/5.png","http://localhost:9000/muse/climb/6.png","http://localhost:9000/muse/climb/7.png","http://localhost:9000/muse/climb/8.png","http://localhost:9000/muse/climb/9.png"]}' http://localhost:3000/inbound/item

# text
# 为什么Rust的热度超过Zig？
curl -X POST -H "Content-Type: application/json" -d '{"text":"为什么Rust的热度超过Zig？Zig也是一个注重内存安全的编程语言，为什么热度不如Rust呢？Zig出来比Rust晚，按理由应该比Rust更优秀。但事实上似乎大家更喜欢Rust，请问为什么？Zig似乎入门门槛更低。如果在很旧的系统上（linux）上编译rust程序，会遇到一个问题就是最新版本rust不支持旧libc了，然后有一个工具是cross，可以以docker为蓝本编译，这个时候发现并不支持超旧版本libc，还是绕不开rustc对libc最低要求。这个时候或许考虑使用no_std制作无依赖包，或者musl（不支持注入和so）。no_std就丢掉了rust的半壁江山，同时本来节省开发时间也拉长了。这个时候请上zig作为linker，神奇的一幕发生了，libc直接就支持了，而且支持so编译，又可以愉快的在各种嵌入式系统上使用rust搞破坏了。rust+zig，完美组合"}' http://localhost:3000/inbound/text
# 为何 Linus 一个人就能写出这么强的系统，中国却做不出来？
curl -X POST -H "Content-Type: application/json" -d '{"text":"为何 Linus 一个人就能写出这么强的系统，中国却做不出来？说实话，是你想多了……Linus确实在Linux的内核开发上做了很多工作，诸如项目发起，最初版内核的设计等等，但是你如今拿到手的任何一个Linux发行版中，包含了至少上百个GNU项目，无数的其它开源项目，以及数十万人贡献的代码。这里所言道的Linux，是指Linux这个内核，而内核这玩意不包括任何应用层，甚至那个黑框框命令行都并不是Linux的一部分。内核暴露的是硬件到软件的抽象、任务和资源调度，给出的是调用系统的编程接口，仅此而已。Linus所做的1991年的第一版内核有些什么功能呢？简单的说，是这样的：一个有着硬件平台限制，能够运行起来的，与当时便不是特别热门的叫做Minix的操作系统内核大部分功能兼容的内核。要说能力，那是非常强的，因为二十多年后的今天的大学生们即使上了操作系统课程做大作业要写个OS内核，通常也不会做得多全面，更不提完全兼容某标准（当然更可能是因为没有做那么精细的需求）。但若只是如此，Linux也就止步于「优秀的大学生课程作业」水平了。真正有意义的是他把Linux扔网上与社区协作开发（后来加上了GPL协议），而后在2年之内有超过百人折腾这个内核。而在当时的商用环境普遍使用Unix而主要发行版的Unix都贵破天际的情况下，在4年后终于有人觉得这个开源内核加上GNU工具能够起到替代部分Unix节省成本，才真正意义上火起来的。而彼时已经有上千人参与内核的开发，其中甚至有大批RH等公司的专职雇员。没错，就这么个内核，没有任何人机交互，仅仅提供软件运行环境的玩意，尽管最初雏形是Linus的作品，四年后已经是数千名对操作系统有研究的程序员共同开发的产物了。而这只是一个现有的Linux发行版中占比重很小的一部分（尽管很重要），可以交互的命令行环境bash来自于GNU，图形界面Gnome来自于GNU，声音服务来自于GNU，显示服务来自于GNU（近来的发行版中也有其它开源实现）……连编译器都来自于GNU，而这些东西，Linus几乎都没有参与。他是大神，是Linux之父，但是说Linux，尤其是现在广泛使用的功能完整的Linux是他一个人开发的这种事情，是不存在的"}' http://localhost:3000/inbound/text
# 苹果到底给了微信什么特权？
curl -X POST -H "Content-Type: application/json" -d '{"text":"苹果到底给了微信什么特权？据我所知有几点：苹果允许微信内置小程序，以及苹果不对微信里充值进行抽成，还有就是iOS系统里面有专门为微信写的一行代码，还加了个注释说不知道微信要干什么用，但这些难道能叫特权吗？我真不明白。我记得内核（Darwin）代码里面有一个空函数，注释是这么说的：这个函数已经弃用了。天知道腾讯为什么要调用它。能让微信在App Store上架就已经是最大的特权了。。。小程序这种东西是不符合苹果审核条款的微信能上架是腾讯和苹果达成了一定的默契换个人早下架了另外充值这块，还是会抽成的当初苹果和微信关于打赏的冲突结果是微信取消公众号打赏后来苹果政策也有调整，打赏的话如果平台不参与抽成苹果也不抽成验证办法也很简单：微信表情里有些是需要用微信豆购买的，解锁表情属于内购要抽成，打赏表情作者不属于内购不抽成微信豆充值是1:0.7"}' http://localhost:3000/inbound/text
# Rustaceans 掀起了 Rust 重写热潮，我们 Javaer 为何不搞个 Java 重写热潮？
curl -X POST -H "Content-Type: application/json" -d '{"text":"Rustaceans 掀起了 Rust 重写热潮，我们 Javaer 为何不搞个 Java 重写热潮？罢拙百言，独尊 Java 不正是我们 Javaer 的追求吗？感谢rust，感谢go，近几年流行的中间件或者基础设施，但凡是用这俩写的（consul,rnacos,minio等等），个个启动飞快，占用内存还少，用起来爽的很。再看一下上一批流行Java写的那些东西，Jenkins，elasticsearch，个个内存起步就是1，2个g，启动还慢的一批，没有对比就没有伤害啊在造轮子这一块，Java应该是没人用了，而且带来的新的好处是由于轮子都是go和rust写的，其他语言都换成用SDK或者grpc，http调用了，c＃开发者也可以享受到对应的生态福利，美的很再补充一个优点，go打包的东西就一个exe，体积还小，还不用装运行环境，随便跨平台，虽然写的人可能不爽，但是用的人还是挺爽的.人家重写是因为Cargo比CMake更好用，代码维护量下降了。用Java重写图啥，重写后代码行数比重写前更长吗？这个理由也不是不可以之前扩张期有一波还真是这样，维护量上升之后需要招更多人，重写架构师就和坐上了升职器一样。但是你看下历史进程，现在大家都在降本增效，你突然跳出来重写是嫌裁员不够猛吗？"}' http://localhost:3000/inbound/text
# 为什么go和rust语言都舍弃了继承？
curl -X POST -H "Content-Type: application/json" -d '{"text":"为什么go和rust语言都舍弃了继承？比如go和rust。两者一个大规模使用，一个大规模好评。我自己的理解，类型是天然的，把类型以及对类型的操作封装在一起也是合理的。但有没有必要以目前oop的方式实现? oop是否是一种过度设计?因为组合优于继承。我们有一只鸭子和一只鸡，他们工作得很好。我们发现鸭子和鸡有很多重复的地方，他们都会飞，都有两只脚两个翅膀，都会唧唧或者嘎嘎叫。于是我们抽象出鸟这个父类，鸭子和鸡都继承了鸟这个父类， 当我们想要在飞的时候额外做点什么，只需要修改鸟就好了，代码得到了缩减，维护起来看似方便了。鸟工作得也很好。我们业务不断扩展，企鹅出现了。 它不会飞，但是会游泳。 鸟的工作出了问题，于是我们把飞行这个功能被下沉到了会飞的鸟类，企鹅继承自一个不会飞的鸟类。接下来橡皮鸭子出现了，人们对于它究竟是不是鸟有了争议。开始浪费时间大量的讨论什么是鸟，鸟该做些什么。（分割线）但我们的生活中没有鸟（请注意这句话），鸟是一个抽象， 我们生活中有鸡，有鸭。我们觉得他们有一些相同的地方，于是把拥有这些相同点的东西叫做鸟，但永远不知道下一个遇见的，能不能算鸟， 鸟的定义要不要修改。这就是继承不适用的原因，让我们看看组合会怎么样。我们找到了鸡和鸭的共同点， 会飞，两只脚，两个翅膀，会叫。 这些东西加上其他的特质『组合』成了鸡或鸭。 会飞这个能力就能提出来，使用在每一个需要飞行能力的地方。 当我遇到企鹅，就不用拿飞行来『组合』它。飞行，不应该是鸡或鸭从父类继承的能力，而应该是『飞行能力』组合成了鸡鸭的一部分。"}' http://localhost:3000/inbound/text

# image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/00470-2991384018-8K%2CThe%20best%20details%2Cmasterpiece%EF%BC%8Ca%20beautiful%20asian%20girl2.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/00476-1731020877-8K%2CThe%20best%20details%2Cmasterpiece%EF%BC%8Ca%20beautiful%20asian%20girl2.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/04834-1549148202-breasts%20solo%20animal%20ears%20thighhighs%20black%20hair%20long%20hair%20tail%20fox%20ears%20ahri%20%20fox%20tail%20%20fox%20girl2__1girl%20ahri%20lea.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/04842-254690438-breasts%20solo%20animal%20ears%20thighhighs%20black%20hair%20long%20hair%20tail%20fox%20ears%20ahri%20%20fox%20tail%20%20fox%20girl2__1girl%20ahri%20lea.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/1515.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/4qess.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/EPS%20%2865%29_thumbnail.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/EmptyName%2024_thumbnail.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/MuseAI%20%E7%94%9F%E6%88%90%E4%BD%9C%E5%93%81%20%2887%29.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/MuseAI_%E7%94%9F%E6%88%90%E4%BD%9C%E5%93%81.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/cute_little_girl2.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/delicate_and_gorgeous_girl2.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/eqrqrq.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/fqz.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/girl2.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/kang.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/poison%E8%88%B9%E9%95%BF%EF%BC%88%E5%89%AF%E6%9C%AC%EF%BC%89.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/rotated-image%20%281%29.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/s60_thumbnail.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/space_girl2_1.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/uy.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/%E4%B8%A4%E5%8D%83%E5%B9%B4.png"}' http://localhost:3000/inbound/image
curl -X POST -H "Content-Type: application/json" -d '{"url": "http://localhost:9000/muse/image/%E5%A4%A7%E7%99%BD%E7%99%BD%E7%B2%A5%E9%87%87%E9%9B%86%E5%88%B0UI-%E9%A3%8E%E6%A0%BC%E5%8C%96.png"}' http://localhost:3000/inbound/image
