# 上海旅游
curl -X POST -H "Content-Type: application/json" -d '{"text":["上海路书｜连夜写的三天行程攻略 一定要看 还有两天就是五一了 连夜整理的攻略一定要看 不多不少，整理了一下三天的行程，这样玩还蛮舒服的，而且近期天气也好，祝大家玩的开心哟       住宿区域       南京路：地铁线密集，步行可到外滩       愚园路：有很多值得打卡的网红小店       陆家嘴：看夜景交通出行       伴手礼选择       ①大白兔奶糖：既是童年的回忆，却又是上海土生士长的糖果       ②城隍庙五香豆：选用余姚县的蚕豆，够香够糯，颗颗饱满       ③高桥松饼：每层的皮薄得像纸，吃起来妙酥，滋味较甜有松软       打卡过的上海美食       蟹叁寳 · 蟹黄捞饭：蟹粉春卷，外面酥酥脆脆的，里面的馅也有蟹粉，肉好嫩       阳春面：味道比较清淡，汤头鲜香可口，本地人都常吃的美食，清淡爽口       生煎包：生煎包可以说是土生土长的上海点心，据说已有上百年的历史       文案来咯       1.       𝑆ℎ𝑎𝑛𝑔ℎ𝑎𝑖       “这座城市就是最好的文案”       2.       𝑆ℎ𝑎𝑛𝑔ℎ𝑎𝑖 ｜初遇上海       3.       SHANGHAI ｜上海·外滩       4.       𝑆ℎ𝑎𝑛𝑔ℎ𝑎𝑖 总要去趟上海 吹吹黄浦江的晚风吧       上海 上海旅游 上海旅游攻略 上海酒店 上海美食 上海住宿 上海旅行 东方明珠 魔都 魔都探店 魔都美食 迪士尼 迪士尼乐园 假期去哪儿 五一去哪玩"],"image":["http://localhost:9000/muse/sh/1.png","http://localhost:9000/muse/sh/2.png","http://localhost:9000/muse/sh/3.png","http://localhost:9000/muse/sh/4.png","http://localhost:9000/muse/sh/5.png","http://localhost:9000/muse/sh/6.png","http://localhost:9000/muse/sh/7.png"]}' http://localhost:3000/inbound/item

# 北京旅游
curl -X POST -H "Content-Type: application/json" -d '{"text":[" 北京旅游攻略日 City walk打卡路线     北京两日city walk路线来啦！！   逛吃拍照 看这一篇就够了   Day1   天坛 门票28 推荐早上8:00入园拍出无人感   天安门广场 记得带上一个小红旗拍照很出片   国家博物馆 需提前预约 建议游玩2h以上   故宫博物院 门票40 提前一周预约   前门大街 适合晚上看看夜景 去逛吃   四季民福 每次去北京都要去这里吃烤鸭      Day2   五四大街 值得逛的店铺有很多 适合city walk   北海公园 门票5 古典的皇家园林   南锣鼓巷 有很多小吃和文艺店铺   鼓楼大街 来看一看赵雷的歌里的鼓楼   颐和园 20 山水亭台楼阁 画中游太美啦   东来顺 这家涮肉味道很不错      关于穿搭：   北京的红色建筑居多   穿黑色系或国风类型的衣服会更出片      关于美食：   涮肉：南门涮肉 八爷涮肉 东来顺   烤鸭：四季民福   炸酱面：方砖厂      关于酒店：   建议故宫附近或靠近地铁站的位置   属于打卡点中心 出行逛吃都方便        北京   北京旅游攻略  北京美食攻略   北京胡同   北京旅游   北京citywalk   北京旅行   北京旅行攻略   北京旅行必打卡景点   天安门   天安门广场   天安门看升旗   国家博物馆   故宫   故宫拍照   北京故宫博物院   北京鼓楼   颐和园   北京颐和园   颐和园攻略   画中游   天坛公园   天坛   祈年殿   天坛公园拍照   北海公园   北锣鼓巷    我的私藏旅行路线   南锣鼓巷   天坛拍照   北京旅游打卡   北京拍照打卡 @走走薯 @生活薯"],"image":["http://localhost:9000/muse/bg/1.png","http://localhost:9000/muse/bg/2.png","http://localhost:9000/muse/bg/3.png","http://localhost:9000/muse/bg/4.png","http://localhost:9000/muse/bg/5.png","http://localhost:9000/muse/bg/6.png","http://localhost:9000/muse/bg/7.png","http://localhost:9000/muse/bg/8.png","http://localhost:9000/muse/bg/9.png","http://localhost:9000/muse/bg/10.png","http://localhost:9000/muse/bg/11.png","http://localhost:9000/muse/bg/12.png","http://localhost:9000/muse/bg/13.png","http://localhost:9000/muse/bg/14.png","http://localhost:9000/muse/bg/15.png","http://localhost:9000/muse/bg/16.png"]}' http://localhost:3000/inbound/item

# 韩国旅游
curl -X POST -H "Content-Type: application/json" -d '{"text":["J人的首尔行｜3天逛吃买我都要！   朋友们都夸的首尔行，一张图就讲清楚啦！我将首尔分为西边，中间，东边三个片区，每天由最北边的景点为起点，一路向南。   天的行程各有主题各有特色！  Day   是核心旅游区，包括了热闹的商圈和传统景点。详细介绍见主页【首尔一日游】。主要路径为【光化门广场】-【景福宫】-【青瓦台】-【韩屋村】-【明洞】-【首尔塔】-【梨泰院】。【路线图见图2！】  Day   大学片区，超级有活力，很好逛！梨花女大真很美！（图5）主要路线为【梨花女子大学】-【延世大学】-【弘益大学】-【汝矣岛汉江公园】【路线图见图3！】  Day   包含了现在最火的打卡点，适合追星人和买买买！主要路线为【东大门设计广场】-【圣水洞】-【清潭洞】-【狎鸥亭】-【新沙洞】【路线图见图4！】   韩国旅游发展局  好好玩情报局   我去韩国撒个欢  红薯旅行家  j人旅行指南  圆周旅迹  首尔旅行  首尔旅游攻略  首尔逛街去哪  首尔探店  jennie同款  韩国旅游攻略  生活薯"],"image":["http://localhost:9000/muse/sk/1.png","http://localhost:9000/muse/sk/2.png","http://localhost:9000/muse/sk/3.png","http://localhost:9000/muse/sk/4.png","http://localhost:9000/muse/sk/5.png","http://localhost:9000/muse/sk/6.png","http://localhost:9000/muse/sk/7.png","http://localhost:9000/muse/sk/8.png","http://localhost:9000/muse/sk/9.png","http://localhost:9000/muse/sk/10.png","http://localhost:9000/muse/sk/11.png"]}' http://localhost:3000/inbound/item

# 爬山
curl -X POST -H "Content-Type: application/json" -d '{"text":["一张图讲清楚日爬泰山路线    春天就要上春山 红色路线：适合体力      步行上下，从红门➡️中天门➡️南天门➡️玉皇顶，再原路返回。爬泰山体验感强。 绿色：适合体力  大巴＋索道上下省时省力，但是只能看到玉皇顶附近景点，沿途景点错过。 红色＋绿色方案一：适合体力   稍费力能欣赏精华景点。从红门爬到中天门，在中天门坐缆车到南天门，步行至玉皇顶。（大多数选择的路线) 红色＋绿色方案二：适合体力    从天外村坐大巴车到中天门，从中天门爬到南天门，步行至玉皇顶。坡度较陡，体验爬山乐趣。 红色＋绿色方案三：适合体力     从红门爬到中天门，再爬到南天门，步行到玉皇顶，返回南天门做索道到中天门，大巴车到天外村。能欣赏全部景点，下山后到市里近。 红色+黄色：适合体力     从红门爬到中天门，再爬到南天门，步行到玉皇顶，返回南天门做索道到桃花源，做大巴到桃花峪，能欣赏全部景点和车览桃花源景色，但是下大巴后打车较远 住宿 建议住在岱庙附近，步行到岱庙几百米，步行到老县衙很近吃各种小吃。炸鸡、串串、麻辣烫、烧饼加肉等，岱庙附近还有夜市一条街。 其他游玩 1.  岱庙：爬泰山必去岱庙。岱庙不是个庙宇，是座有前年历史的古建筑群。 2.  泰安老街：名字叫老街，但是新建的，步行街标配的小吃！小吃街后面的公园灯光挺好看的！ 纪念品 可以买可爱的小狮子泰山石敢当做纪念品，泰山上的价格不如岱庙的便宜。  人文景点分享  泰山  泰山攻略  泰山旅游  泰山石敢当  泰山日爬"],"image":["http://localhost:9000/muse/climb/1.png","http://localhost:9000/muse/climb/2.png","http://localhost:9000/muse/climb/3.png","http://localhost:9000/muse/climb/4.png","http://localhost:9000/muse/climb/5.png","http://localhost:9000/muse/climb/6.png","http://localhost:9000/muse/climb/7.png","http://localhost:9000/muse/climb/8.png","http://localhost:9000/muse/climb/9.png"]}' http://localhost:3000/inbound/item
